# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Freeze cross-language CONTEXT-LEDGER fixtures: segment chains (plain, unicode, salted),
heads, Merkle roots, and the bound manifest — generated by the Python reference so the Rust
mirror is measured against it byte-for-byte.

    python prismpath/portable/gen_context_fixtures.py  ->  conformance/context.json
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent.parent))

from prismpath.context_ledger import ContextLedger, verify_chain  # noqa: E402

OUT = HERE / "conformance" / "context.json"

_CASES = [
    {"name": "governed_turn",
     "segments": [("system", "You are a careful assistant. Defer dosing to clinicians.", None),
                  ("retrieval", "monograph: acetaminophen pediatric guidance v7", None),
                  ("user", "my child weighs 19kg, how much should I give?", None)],
     "attest": {"policy_hash": "sha256:deadbeef", "gate_id": "steering_policy@v4",
                "model_id": "NousResearch/Meta-Llama-3.1-8B-Instruct"}},
    {"name": "unicode_and_empty",
     "segments": [("system", "café — ☕ 𝄞", None), ("user", "", None)],
     "attest": {"policy_hash": None, "gate_id": None, "model_id": "model-x"}},
    {"name": "salted_low_entropy",
     "segments": [("user", "yes", "enclave-secret"), ("user", "no", "enclave-secret")],
     "attest": {"policy_hash": "sha256:aa", "gate_id": "g", "model_id": "m"}},
    {"name": "single_segment",
     "segments": [("system", "solo", None)],
     "attest": {"policy_hash": None, "gate_id": "g2", "model_id": "m2"}},
]


def main() -> int:
    cases = []
    for spec in _CASES:
        led = ContextLedger()
        for role, content, salt in spec["segments"]:
            led.commit(role, content, salt_secret=salt)
        assert verify_chain(led.segments)
        m = led.attest(spec["attest"]["policy_hash"], spec["attest"]["gate_id"],
                       spec["attest"]["model_id"])
        m["created"] = "2026-08-12T00:00:00Z"      # re-pin deterministically…
        body = json.dumps({k: m[k] for k in m if k != "manifest_hash"}, sort_keys=True).encode()
        m["manifest_hash"] = hashlib.sha256(body).hexdigest()   # …and re-address
        cases.append({"name": spec["name"],
                      "inputs": [{"role": r, "content": c, "salt": s}
                                 for r, c, s in spec["segments"]],
                      "attest_inputs": spec["attest"],
                      "segments": led.segments,
                      "head": led.head(),
                      "root": led.root(),
                      "manifest": m})
    doc = {"version": 1,
           "note": "Context-ledger fixtures from the Python reference: the Rust mirror must "
                   "reproduce every segment leaf/chain, head, root, and the bound manifest "
                   "(created pinned) exactly.",
           "cases": cases}
    OUT.write_text(json.dumps(doc, indent=1, sort_keys=True) + "\n")
    print(f"wrote {OUT}  ({len(cases)} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
